# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mode_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='raw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(max_length=100)),
                ('material_name', models.CharField(max_length=100)),
                ('purchase_name', models.CharField(max_length=100)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('factory_wise_bifercation', models.CharField(max_length=100)),
                ('ex_factory_price', models.FloatField(default=0)),
                ('supplier_name', models.CharField(max_length=100)),
                ('hsn_code', models.CharField(max_length=100)),
                ('gst', models.FloatField(default=0)),
                ('price_after_gst', models.FloatField(default=0)),
                ('transpoter', models.CharField(max_length=100)),
                ('freight', models.FloatField(default=0)),
                ('cost_price', models.FloatField(default=0)),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mode_master.mode')),
            ],
        ),
    ]
