# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-14 15:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='profit',
            name='pl_sheet',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profit',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
    ]
