# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-20 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180314_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='end_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profit',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
