# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_cost_price', models.IntegerField(default=0)),
                ('product_name', models.CharField(max_length=100)),
                ('product_code', models.CharField(max_length=100)),
                ('factory_name', models.CharField(max_length=100)),
                ('pack_size', models.CharField(max_length=100)),
                ('raw_id', models.IntegerField(default=0)),
                ('rawmultiplier', models.FloatField(default=0)),
                ('wastage', models.FloatField(default=0)),
                ('overall_wastage', models.FloatField(default=0)),
                ('margin_per', models.FloatField(default=0)),
                ('margin_amount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='costpack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packing_id', models.IntegerField(default=0)),
                ('multipliar', models.FloatField(default=0)),
                ('last_updated_on', models.DateTimeField(auto_now_add=True)),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing_cost_master.cost')),
            ],
        ),
    ]
