# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing_cost_master', '0003_cost_cost_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cost',
            old_name='cost_model',
            new_name='helo',
        ),
    ]
