# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing_cost_master', '0004_auto_20180220_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='mrp_price',
            field=models.FloatField(default=0),
        ),
    ]
