# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing_cost_master', '0007_auto_20180221_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cost',
            old_name='raw_id',
            new_name='rt_id',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='helo',
        ),
    ]
