# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing_cost_master', '0009_cost_raw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cost',
            old_name='raw',
            new_name='Raw',
        ),
    ]
