# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-24 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mode_master', '0001_initial'),
        ('manufacturing_cost_master', '0011_costpack_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='costpack',
            name='Head',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mode_master.head'),
            preserve_default=False,
        ),
    ]
